# Generated by Django 2.1.4 on 2019-05-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.CharField(max_length=20, verbose_name='网关id')),
                ('description', models.CharField(max_length=200, verbose_name='网关描述')),
            ],
        ),
    ]
