# Generated by Django 2.1.4 on 2019-05-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gateway',
            new_name='GatewayBase',
        ),
    ]
