# Generated by Django 2.1.4 on 2019-05-30 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_auto_20190530_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatewaybase',
            name='gateway_id',
        ),
        migrations.AddField(
            model_name='gatewaybase',
            name='create_date',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='gatewaybase',
            name='gateway_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='网关名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gatewaybase',
            name='sub_device',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
