# Generated by Django 2.1.4 on 2019-05-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_auto_20190530_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaybase',
            name='create_date',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='gatewaybase',
            name='sub_device',
            field=models.IntegerField(default=0),
        ),
    ]
