# Generated by Django 2.1.4 on 2019-05-31 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_auto_20190530_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaybase',
            name='create_date',
            field=models.DateField(default=datetime.date.today, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='gatewaybase',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='网关描述'),
        ),
    ]
