# Generated by Django 2.1.4 on 2019-05-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_auto_20190531_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatewaybase',
            name='id',
        ),
        migrations.AlterField(
            model_name='gatewaybase',
            name='gateway_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='网关名'),
        ),
    ]
