# Generated by Django 2.1.4 on 2019-06-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_auto_20190531_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(default='', verbose_name='Topic')),
                ('function', models.CharField(max_length=10, verbose_name='功能')),
                ('tag', models.CharField(max_length=20, null=True, verbose_name='标签')),
                ('description', models.TextField(default='', max_length=200)),
            ],
        ),
    ]
