# Generated by Django 2.1.4 on 2019-06-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_mqtttopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtttopic',
            name='tag',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='标签'),
        ),
    ]
