# Generated by Django 2.1.4 on 2019-05-31 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateway', '0005_auto_20190531_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCP_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=20)),
                ('slave_id', models.IntegerField()),
                ('create_time', models.DateField()),
                ('last_active', models.DateField(auto_now=True)),
                ('gateway_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.GatewayBase')),
            ],
        ),
    ]
