# Generated by Django 2.1.4 on 2019-05-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcp_device',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='设备描述'),
        ),
        migrations.AddField(
            model_name='tcp_device',
            name='protocol_way',
            field=models.CharField(default='TCP', max_length=3, verbose_name='设备接入方式'),
            preserve_default=False,
        ),
    ]
