# Generated by Django 2.1.4 on 2019-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_rtu_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtu_device',
            name='work_flag',
            field=models.BooleanField(default=True, verbose_name='激活状态'),
        ),
        migrations.AddField(
            model_name='tcp_device',
            name='work_flag',
            field=models.BooleanField(default=True, verbose_name='激活状态'),
        ),
    ]
