# Generated by Django 2.1.4 on 2019-06-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20190602_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('identifier', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
