# Generated by Django 2.1.4 on 2019-06-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
