# Generated by Django 2.1.4 on 2019-06-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_devicetask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetask',
            name='device_name',
        ),
        migrations.AddField(
            model_name='devicetask',
            name='slave_id',
            field=models.IntegerField(default=1),
        ),
    ]
