# Generated by Django 2.1.4 on 2019-06-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20190605_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetask',
            name='address',
        ),
        migrations.AlterField(
            model_name='devicetask',
            name='slave_id',
            field=models.IntegerField(default=1, verbose_name='设备地址'),
        ),
    ]
