# Generated by Django 2.1.4 on 2019-06-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20190605_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetask',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
