# Generated by Django 2.1.4 on 2019-06-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20190605_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='compute',
            field=models.TextField(default='', max_length=200, verbose_name='计算公式'),
        ),
    ]
